/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.85
 * Generated at: 2024-03-08 10:09:51 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.views.admin;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class dashboard_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(1);
    _jspx_dependants.put("/WEB-INF/views/admin/../navbar.jspf", Long.valueOf(1708606796269L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "Les JSPs ne permettent que GET, POST ou HEAD. Jasper permet aussi OPTIONS");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html;charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("    <head>\r\n");
      out.write("        <meta http-equiv=\"Content-Type\" content=\"text/html; charset=UTF-8\">\r\n");
      out.write("        <title>Admin Dashboard</title>\r\n");
      out.write("\r\n");
      out.write("        <link rel=\"stylesheet\" href=\"/SpringApp/bootstrap/css/bootstrap.css\">\r\n");
      out.write("        <!-- Bootstrap Table -->\r\n");
      out.write("        <link rel=\"stylesheet\" href=\"/SpringApp/bootstrap-table/dist/bootstrap-table.min.css\">\r\n");
      out.write("        <link rel=\"stylesheet\" href=\"/SpringApp/bootstrap-icons/font/bootstrap-icons.css\">\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("        <link rel=\"stylesheet\" href=\"/SpringApp/css/main.css\">\r\n");
      out.write("        <!-- Mandatory to use the sidebar -->\r\n");
      out.write("        <link rel=\"stylesheet\" href=\"/SpringApp/css/sidebar.css\">\r\n");
      out.write("        <link rel=\"stylesheet\" href=\"/SpringApp/fontawesome/css/all.css\">\r\n");
      out.write("\r\n");
      out.write("        <script src=\"/SpringApp/js/test.js\"></script>\r\n");
      out.write("\r\n");
      out.write("        <script type=\"text/javascript\" src=\"/SpringApp/js/jquery-3.3.1.min.js\"></script>\r\n");
      out.write("        <script src=\"https://cdn.jsdelivr.net/npm/popper.js@1.12.9/dist/umd/popper.min.js\" integrity=\"sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q\" crossorigin=\"anonymous\"></script>\r\n");
      out.write("        <script type=\"text/javascript\" src=\"/SpringApp/bootstrap/js/bootstrap.min.js\"></script>\r\n");
      out.write("        <script src=\"https://unpkg.com/tableexport.jquery.plugin/tableExport.min.js\"></script>\r\n");
      out.write("\r\n");
      out.write("        <link rel=\"shortcut icon\" href=\"favicon.ico\">\r\n");
      out.write("    </head>\r\n");
      out.write("    <body>\r\n");
      out.write("        \r\n");
      out.write("\r\n");
      out.write("        ");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<nav class=\"navbar navbar-dark d-flex justify-content-space-between sticky-top\">\r\n");
      out.write("    <div class=\"navbar-brand\">\r\n");
      out.write("        <button id=\"menu-toggle\" class=\"navbar-toggler mr-3 text-white\" type=\"button\" aria-label=\"Toggle navigation\" data-toggle-sidebar=\"MainSidebar\">\r\n");
      out.write("            <span class=\"navbar-toggler-icon text-white\"></span>\r\n");
      out.write("        </button>\r\n");
      out.write("        <a href=\"/SpringApp/homepage.do\">\r\n");
      out.write("            <img src=\"/SpringApp/img/logo.png\" height=\"40\" alt=\"\">\r\n");
      out.write("        </a>\r\n");
      out.write("    </div>\r\n");
      out.write("\r\n");
      out.write("    <a class=\"navbar-brand\" href=\"/SpringApp/login.do\">\r\n");
      out.write("        <i class=\"fa fa-user icon\"></i>\r\n");
      out.write("    </a>\r\n");
      out.write("</nav>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("        <div id=\"page\" class=\"active\">\r\n");
      out.write("            <div id=\"Sidebar\">\r\n");
      out.write("                <!-- \r\n");
      out.write("                    DO NOT CHANGE DIV ID\r\n");
      out.write("                    The content of the sidebar will be loaded here\r\n");
      out.write("                    See navbar.jsp to modify the sidebar -->\r\n");
      out.write("                    <div id=\"sidebar_loader\" class=\"sidebar pt-5 d-flex justify-content-center\" aria-label=\"Main sidebar containing navigation links and some information\" aria-hidden=\"false\">\r\n");
      out.write("                        <div class=\"sidebar__content\">\r\n");
      out.write("                            <div class=\"spinner-border\" role=\"status\">\r\n");
      out.write("                                <span class=\"sr-only\">Loading...</span>\r\n");
      out.write("                            </div>\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                \r\n");
      out.write("            </div>\r\n");
      out.write("            \r\n");
      out.write("            <!-- Page content : YOU MUST PUT THE CONTENT OF THE PAGE HERE -->\r\n");
      out.write("            <div class=\"page-content\">\r\n");
      out.write("                <div class=\"container-fluid\">\r\n");
      out.write("                    <div class=\"row\">\r\n");
      out.write("                        <div class=\"col-lg-12 pt-3\">\r\n");
      out.write("                            <div class=\"row \">\r\n");
      out.write("                                <div class=\"col-lg-12 d-flex justify-content-center\">\r\n");
      out.write("                                    <img src=\"img/logo.png\" alt=\"\" class=\"logo\" width=\"200px\">\r\n");
      out.write("                                </div>\r\n");
      out.write("                                \r\n");
      out.write("                            </div>\r\n");
      out.write("                            \r\n");
      out.write("                            <div class=\"row d-flex justify-content-center pt-2 text-center\">\r\n");
      out.write("                                <div class=\"col-xl-7\">\r\n");
      out.write("                                    <h2>Bienvenue dans votre dashboard !</h2>\r\n");
      out.write("                                    <hr>\r\n");
      out.write("                                </div>\r\n");
      out.write("                            </div>\r\n");
      out.write("                        </div>\r\n");
      out.write("\r\n");
      out.write("                    </div>\r\n");
      out.write("                    <div class=\"row d-flex justify-content-center\">\r\n");
      out.write("                        <div class=\"col-xl-5 pt-3\">\r\n");
      out.write("                            <div class=\"box pt-2 mx-4\">\r\n");
      out.write("                                <div class=\"row d-flex justify-content-center pb-4 mx-2\">\r\n");
      out.write("                                    <div class=\"col-lg-12\">\r\n");
      out.write("                                        \r\n");
      out.write("                                        <h4>Import des fichiers .json</h4>\r\n");
      out.write("                                        <form method=\"POST\" action=\"uploadMultipleFiles.do\" enctype=\"multipart/form-data\">\r\n");
      out.write("                                            <div class=\"form-group pt-2\">\r\n");
      out.write("                                                <!-- <label for=\"exampleInputEmail1\">Fichiers à ajouter</label> -->\r\n");
      out.write("                                                <input type=\"file\" class=\"form-control\" id=\"file_upload\" name=\"file\" multiple aria-describedby=\"uploadHelp\">\r\n");
      out.write("                                                <small id=\"uploadHelp\" class=\"form-text text-muted\">Sélectionnez tous les fichiers .json que vous voulez importer</small>\r\n");
      out.write("                                            </div>\r\n");
      out.write("\r\n");
      out.write("                                            <button type=\"submit\" class=\"btn btn-primary w-100\">Upload</button>\r\n");
      out.write("\r\n");
      out.write("                                        </form>\r\n");
      out.write("                                    </div>\r\n");
      out.write("                                </div>\r\n");
      out.write("                            </div>\r\n");
      out.write("                            \r\n");
      out.write("                        </div>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("                        <div class=\"col-xl-5 pt-3\">\r\n");
      out.write("                            <div class=\"box pt-2 mx-4\">\r\n");
      out.write("                                <div class=\"row d-flex justify-content-center pb-4 mx-2\">\r\n");
      out.write("                                    <div class=\"col-lg-12\">\r\n");
      out.write("                                        \r\n");
      out.write("                                        <h4>Génération des synthèses</h4>\r\n");
      out.write("                                        <div class=\"alert alert-warning\" role=\"alert\">\r\n");
      out.write("                                            Il faut importer les fichiers json avant de générer les synthèses !\r\n");
      out.write("                                        </div>\r\n");
      out.write("                                        <button type=\"button\" class=\"btn btn-primary w-100\" onclick=\"generateSynthesis()\">Générer</button>\r\n");
      out.write("                                        <div id=\"synthesis_loader\" class=\"py-3\" hidden>\r\n");
      out.write("                                            <div class=\"spinner-border text-secondary\" role=\"status\">\r\n");
      out.write("                                                <span class=\"sr-only\">Loading...</span>\r\n");
      out.write("                                            </div>\r\n");
      out.write("                                        </div>\r\n");
      out.write("                                    </div>\r\n");
      out.write("                                </div>\r\n");
      out.write("                            </div>\r\n");
      out.write("                            \r\n");
      out.write("                        </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                    <div class=\"row d-flex justify-content-center\">\r\n");
      out.write("                        <div class=\"col-xl-10 pt-3\">\r\n");
      out.write("                            <div class=\"box pt-2 mx-4\">\r\n");
      out.write("                                <div class=\"row d-flex justify-content-center pb-4 mx-2\">\r\n");
      out.write("                                    <div class=\"col-lg-12\">\r\n");
      out.write("                                        \r\n");
      out.write("                                        <h4>Envois des mails</h4>\r\n");
      out.write("                                        <div class=\"alert alert-warning\" role=\"alert\">\r\n");
      out.write("                                            Il faut importer les fichiers json et générer les synthèses avant d'envoyer les mails !\r\n");
      out.write("                                        </div>\r\n");
      out.write("                                        \r\n");
      out.write("                                        <form class=\"needs-validation\" novalidate   >\r\n");
      out.write("                                            <div class=\"form-group row\">\r\n");
      out.write("                                                <label for=\"destinataire\" class=\"col-lg-4 col-form-label\">Adresse e-mail du destinataire:</label>\r\n");
      out.write("                                                <div class=\"col-lg-8\">\r\n");
      out.write("                                                    <input type=\"email\" id=\"destinataire\" name=\"destinataire\" class=\"form-control\" required>\r\n");
      out.write("                                                    <div class=\"invalid-feedback\">\r\n");
      out.write("                                                        Veuillez renseignez une adresse mail valide.\r\n");
      out.write("                                                    </div>\r\n");
      out.write("                                                </div>\r\n");
      out.write("                                            </div>\r\n");
      out.write("                                            <hr>\r\n");
      out.write("                                            <div class=\"form-group row\">\r\n");
      out.write("                                                <label for=\"username\" class=\"col-lg-4 col-form-label\">Adresse e-mail :</label>\r\n");
      out.write("                                                <div class=\"col-lg-8\">\r\n");
      out.write("                                                    <input type=\"email\" id=\"username\" name=\"username\" class=\"form-control\" required>\r\n");
      out.write("                                                    <div class=\"invalid-feedback\">\r\n");
      out.write("                                                        Veuillez renseignez une adresse mail valide.\r\n");
      out.write("                                                    </div>\r\n");
      out.write("                                                </div>\r\n");
      out.write("                                            </div>\r\n");
      out.write("                                            <div class=\"form-group row\">\r\n");
      out.write("                                                <label for=\"password\" class=\"col-lg-4 col-form-label\">Mot de passe :</label>\r\n");
      out.write("                                                <div class=\"col-lg-8\">\r\n");
      out.write("                                                    <input type=\"password\" id=\"password\" name=\"password\" class=\"form-control\" required>\r\n");
      out.write("                                                    <div class=\"invalid-feedback\">\r\n");
      out.write("                                                        Le mot de passe est requis.\r\n");
      out.write("                                                    </div>\r\n");
      out.write("                                                </div>\r\n");
      out.write("                                                \r\n");
      out.write("                                            \r\n");
      out.write("                                            </div>\r\n");
      out.write("                                            <hr>\r\n");
      out.write("                                            <div class=\"form-group\">\r\n");
      out.write("                                                <label for=\"mailObject\">Objet</label>\r\n");
      out.write("                                                <input type=\"text\" class=\"form-control\" id=\"mailObject\" placeholder=\"\">\r\n");
      out.write("                                              </div>\r\n");
      out.write("                                            \r\n");
      out.write("                                            <div class=\"form-group\">\r\n");
      out.write("                                                <label for=\"mailContent\">Contenu du mail</label>\r\n");
      out.write("                                                <textarea class=\"form-control\" id=\"mailContent\" rows=\"3\">Template to be defined ...</textarea>\r\n");
      out.write("                                            </div>\r\n");
      out.write("                                            <button type=\"submit\" class=\"btn btn-primary w-100\">Envoyer les mails</button>\r\n");
      out.write("                                        </form>\r\n");
      out.write("                                        \r\n");
      out.write("                                        <div id=\"mails_loader\" class=\"py-3\" hidden>\r\n");
      out.write("                                            <div class=\"spinner-border text-secondary\" role=\"status\">\r\n");
      out.write("                                                <span class=\"sr-only\">Loading...</span>\r\n");
      out.write("                                            </div>\r\n");
      out.write("                                        </div>\r\n");
      out.write("                                    </div>\r\n");
      out.write("                                </div>\r\n");
      out.write("                            </div>\r\n");
      out.write("                        </div>\r\n");
      out.write("\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("        </div>\r\n");
      out.write("        \r\n");
      out.write("\r\n");
      out.write("    </body>\r\n");
      out.write("\r\n");
      out.write("    <script>\r\n");
      out.write("        // Example starter JavaScript for disabling form submissions if there are invalid fields\r\n");
      out.write("        (function() {\r\n");
      out.write("          'use strict';\r\n");
      out.write("          window.addEventListener('load', function() {\r\n");
      out.write("            // Fetch all the forms we want to apply custom Bootstrap validation styles to\r\n");
      out.write("            var forms = document.getElementsByClassName('needs-validation');\r\n");
      out.write("            // Loop over them and prevent submission\r\n");
      out.write("            var validation = Array.prototype.filter.call(forms, function(form) {\r\n");
      out.write("              form.addEventListener('submit', function(event) {\r\n");
      out.write("                if (form.checkValidity() === false) {\r\n");
      out.write("                  event.preventDefault();\r\n");
      out.write("                  event.stopPropagation();\r\n");
      out.write("                }\r\n");
      out.write("                form.classList.add('was-validated');\r\n");
      out.write("              }, false);\r\n");
      out.write("            });\r\n");
      out.write("          }, false);\r\n");
      out.write("        })();\r\n");
      out.write("    </script>\r\n");
      out.write("\r\n");
      out.write("    <script>\r\n");
      out.write("        function generateSynthesis() {\r\n");
      out.write("            console.log(\"test\");\r\n");
      out.write("            $.ajax({\r\n");
      out.write("                'url': '/SpringApp/admin/generateSynthesis.do',\r\n");
      out.write("                'type': 'post',\r\n");
      out.write("                'datatype': 'html',\r\n");
      out.write("                beforeSend: function() {\r\n");
      out.write("                    $(\"#synthesis_loader\").show();\r\n");
      out.write("                },\r\n");
      out.write("                success: function(msg) {\r\n");
      out.write("                    $(\"#sidebar_loader\").hide();\r\n");
      out.write("                }\r\n");
      out.write("            })\r\n");
      out.write("            .done(function (response) {\r\n");
      out.write("                console.log(response);\r\n");
      out.write("            })\r\n");
      out.write("            return true\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        function sendMails() {\r\n");
      out.write("            console.log(\"test\");\r\n");
      out.write("            $.ajax({\r\n");
      out.write("                'url': '/SpringApp/admin/sendMails.do',\r\n");
      out.write("                'type': 'post',\r\n");
      out.write("                'datatype': 'html',\r\n");
      out.write("                beforeSend: function() {\r\n");
      out.write("                    $(\"#mails_loader\").show();\r\n");
      out.write("                },\r\n");
      out.write("                success: function(msg) {\r\n");
      out.write("                    $(\"#mails_loader\").hide();\r\n");
      out.write("                }\r\n");
      out.write("            })\r\n");
      out.write("            return true\r\n");
      out.write("        }\r\n");
      out.write("    </script>\r\n");
      out.write("\r\n");
      out.write("    <script>\r\n");
      out.write("        $.ajax({\r\n");
      out.write("            'url': '/SpringApp/sidebar.do',\r\n");
      out.write("            'type': 'get',\r\n");
      out.write("            'dataType': 'html',\r\n");
      out.write("            beforeSend: function() {\r\n");
      out.write("                $(\"#sidebar_loader\").show();\r\n");
      out.write("                $(\"#sidebar_loader\").attr('aria-hidden', false);\r\n");
      out.write("            },\r\n");
      out.write("            success: function(msg) {\r\n");
      out.write("                $(\"#sidebar_loader\").hide();\r\n");
      out.write("                $(\"#sidebar_loader\").attr('aria-hidden', true);\r\n");
      out.write("            }\r\n");
      out.write("        })\r\n");
      out.write("        .done(function (response) {\r\n");
      out.write("            $('#Sidebar').append(response);\r\n");
      out.write("        })\r\n");
      out.write("    </script>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("        \r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
