/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.85
 * Generated at: 2024-03-04 11:02:36 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.views;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class surveySynthesis_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(3);
    _jspx_dependants.put("jar:file:/C:/Users/Alex/Documents/COURS/EI3/ECNAutoSurvey/SpringApp/target/SpringApp-1.0/WEB-INF/lib/jstl-1.2.jar!/META-INF/c.tld", Long.valueOf(1153377882000L));
    _jspx_dependants.put("/WEB-INF/lib/jstl-1.2.jar", Long.valueOf(1153506114000L));
    _jspx_dependants.put("/WEB-INF/views/navbar.jspf", Long.valueOf(1708606796269L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005fset_0026_005fvar_005fvalue_005fnobody;

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
    _005fjspx_005ftagPool_005fc_005fset_0026_005fvar_005fvalue_005fnobody = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
  }

  public void _jspDestroy() {
    _005fjspx_005ftagPool_005fc_005fset_0026_005fvar_005fvalue_005fnobody.release();
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "Les JSPs ne permettent que GET, POST ou HEAD. Jasper permet aussi OPTIONS");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html;charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      if (_jspx_meth_c_005fset_005f0(_jspx_page_context))
        return;
      out.write('\n');
      if (_jspx_meth_c_005fset_005f1(_jspx_page_context))
        return;
      out.write('\n');
      if (_jspx_meth_c_005fset_005f2(_jspx_page_context))
        return;
      out.write("\n");
      out.write("<!DOCTYPE html>\n");
      out.write("<html>\n");
      out.write("    <head>\n");
      out.write("        <meta http-equiv=\"Content-Type\" content=\"text/html; charset=UTF-8\">\n");
      out.write("        <title>Accueil</title>\n");
      out.write("\n");
      out.write("        <link rel=\"stylesheet\" href=\"/SpringApp/bootstrap/css/bootstrap.css\">\n");
      out.write("        <!-- Bootstrap Table -->\n");
      out.write("        <link rel=\"stylesheet\" href=\"/SpringApp/bootstrap-table/dist/bootstrap-table.min.css\">\n");
      out.write("        <link rel=\"stylesheet\" href=\"/SpringApp/bootstrap-icons/font/bootstrap-icons.css\">\n");
      out.write("\n");
      out.write("\n");
      out.write("        <link rel=\"stylesheet\" href=\"/SpringApp/css/main.css\">\n");
      out.write("        <!-- Mandatory to use the sidebar -->\n");
      out.write("        <link rel=\"stylesheet\" href=\"/SpringApp/css/sidebar.css\">\n");
      out.write("        <link rel=\"stylesheet\" href=\"/SpringApp/fontawesome/css/all.css\">\n");
      out.write("\n");
      out.write("        <script src=\"/SpringApp/js/test.js\"></script>\n");
      out.write("\n");
      out.write("        <script type=\"text/javascript\" src=\"/SpringApp/js/jquery-3.3.1.min.js\"></script>\n");
      out.write("        <script src=\"https://cdn.jsdelivr.net/npm/popper.js@1.12.9/dist/umd/popper.min.js\" integrity=\"sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q\" crossorigin=\"anonymous\"></script>\n");
      out.write("        <script type=\"text/javascript\" src=\"/SpringApp/bootstrap/js/bootstrap.min.js\"></script>\n");
      out.write("        <script src=\"https://unpkg.com/tableexport.jquery.plugin/tableExport.min.js\"></script>\n");
      out.write("\n");
      out.write("        <link rel=\"shortcut icon\" href=\"favicon.ico\">\n");
      out.write("    </head>\n");
      out.write("    <body>\n");
      out.write("        \n");
      out.write("\n");
      out.write("        ");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<nav class=\"navbar navbar-dark d-flex justify-content-space-between sticky-top\">\r\n");
      out.write("    <div class=\"navbar-brand\">\r\n");
      out.write("        <button id=\"menu-toggle\" class=\"navbar-toggler mr-3 text-white\" type=\"button\" aria-label=\"Toggle navigation\" data-toggle-sidebar=\"MainSidebar\">\r\n");
      out.write("            <span class=\"navbar-toggler-icon text-white\"></span>\r\n");
      out.write("        </button>\r\n");
      out.write("        <a href=\"/SpringApp/homepage.do\">\r\n");
      out.write("            <img src=\"/SpringApp/img/logo.png\" height=\"40\" alt=\"\">\r\n");
      out.write("        </a>\r\n");
      out.write("    </div>\r\n");
      out.write("\r\n");
      out.write("    <a class=\"navbar-brand\" href=\"/SpringApp/login.do\">\r\n");
      out.write("        <i class=\"fa fa-user icon\"></i>\r\n");
      out.write("    </a>\r\n");
      out.write("</nav>\r\n");
      out.write("\n");
      out.write("\n");
      out.write("        <div id=\"page\" class=\"active\">\n");
      out.write("            <div id=\"Sidebar\">\n");
      out.write("                <!-- \n");
      out.write("                    DO NOT CHANGE DIV ID\n");
      out.write("                    The content of the sidebar will be loaded here\n");
      out.write("                    See navbar.jsp to modify the sidebar -->\n");
      out.write("                    <div id=\"sidebar_loader\" class=\"sidebar pt-5 d-flex justify-content-center\" aria-label=\"Main sidebar containing navigation links and some information\" aria-hidden=\"false\">\n");
      out.write("                        <div class=\"sidebar__content\">\n");
      out.write("                            <div class=\"spinner-border\" role=\"status\">\n");
      out.write("                                <span class=\"sr-only\">Loading...</span>\n");
      out.write("                            </div>\n");
      out.write("                        </div>\n");
      out.write("                    </div>\n");
      out.write("                \n");
      out.write("            </div>\n");
      out.write("            \n");
      out.write("            <!-- Page content : YOU MUST PUT THE CONTENT OF THE PAGE HERE -->\n");
      out.write("            <div class=\"page-content\">\n");
      out.write("                <div class=\"container-fluid px-5\">\n");
      out.write("                    <div class=\"row d-flex justify-content-center text-center\">\n");
      out.write("                        <div class=\"col-xl-10\">\n");
      out.write("                            <h1>PGROU</h1>\n");
      out.write("                            <hr>\n");
      out.write("                        </div>\n");
      out.write("                    </div>\n");
      out.write("                    <div class=\"form-group row\">\n");
      out.write("                        <label for=\"subjectName\" class=\"col-lg-2 col-form-label\">Titre de la matière</label>\n");
      out.write("                        <div class=\"col-lg-3\">\n");
      out.write("                            <input name=\"subjectName\" type=\"text\" readonly class=\"form-control\" id=\"subjectName\" value=\"PGROU\">\n");
      out.write("                        </div>\n");
      out.write("                    </div>\n");
      out.write("\n");
      out.write("                    <div class=\"form-group row\">\n");
      out.write("                        <label for=\"subjectCursus\" class=\"col-lg-2 col-form-label\">Cursus</label>\n");
      out.write("                        <div class=\"col-lg-3\">\n");
      out.write("                            <input name=\"subjectCursus\" type=\"text\" readonly class=\"form-control\" id=\"subjectCursus\" value=\"INGE GEN\">\n");
      out.write("                        </div>\n");
      out.write("                    </div>\n");
      out.write("\n");
      out.write("                    <div class=\"form-group row\">\n");
      out.write("                        <label for=\"subjectYear\" class=\"col-lg-2 col-form-label\">Année</label>\n");
      out.write("                        <div class=\"col-lg-3\">\n");
      out.write("                            <input name=\"subjectYear\" type=\"text\" readonly class=\"form-control\" id=\"subjectYear\" value=\"2022-2023\">\n");
      out.write("                        </div>\n");
      out.write("                    </div>\n");
      out.write("\n");
      out.write("                    <div class=\"row pt-2\">\n");
      out.write("                        <div class=\"col-xl-5\">\n");
      out.write("                            <h4>I. Synthèse de l'évaluation</h4>\n");
      out.write("                            <hr>\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("                        </div>\n");
      out.write("                    </div>\n");
      out.write("\n");
      out.write("                    <div class=\"row pt-3\">\n");
      out.write("                        <div class=\"col-xl-12\">\n");
      out.write("                            <h5 class=\"font-weight-bold\">Taux de réponse\n");
      out.write("                                <br>\n");
      out.write("                                <small class=\"text-muted\">(moyenne,  sur l'ensemble des questions, du nombre de réponses exprimées / nombre d'inscrits dans la matière)</small>\n");
      out.write("                            </h5>\n");
      out.write("\n");
      out.write("                            <div>Le taux de réponse à l'enquête est de (pour un total de 188 étudiants inscrits) :\n");
      out.write("                                <ul>\n");
      out.write("                                    <li>41 % pour les réponses complètes.</li>\n");
      out.write("                                    <li>44 % pour les réponses partielles.</li>\n");
      out.write("                                </ul>\n");
      out.write("                            </div>\n");
      out.write("                        </div>\n");
      out.write("                    </div>\n");
      out.write("\n");
      out.write("                    <div class=\"row pt-3\">\n");
      out.write("                        <div class=\"col-xl-12\">\n");
      out.write("                            <h5 class=\"font-weight-bold\">Appréciation globale</h5>\n");
      out.write("\n");
      out.write("                            <div>Qualité globale de l'enseignement : <span id=\"satisfactoryPercentage\">77</span> % des étudiants sont satisfaits.</div>\n");
      out.write("                        </div>\n");
      out.write("                    </div>\n");
      out.write("\n");
      out.write("                    <div class=\"row pt-3\">\n");
      out.write("                        <div class=\"col-xl-12\">\n");
      out.write("                            <h5 class=\"font-weight-bold\">Les points positifs\n");
      out.write("                                <br>\n");
      out.write("                                <small class=\"text-muted\">(% : réponses tout à fait d'accord et plutôt d'accord sur les réponses exprimées)</small>\n");
      out.write("                            </h5>\n");
      out.write("\n");
      out.write("                            <div>Le taux de réponse à l'enquête est de (pour un total de 188 étudiants inscrits) :\n");
      out.write("                                <ul>\n");
      out.write("                                    <li>Cette matière est utile à la formation d'ingénieur généraliste (87 %)</li>\n");
      out.write("                                    <li>Le niveau des connaissances exigé en projet est approprié (87 %)</li>\n");
      out.write("                                    <li>L'enseignement est bien adapté à mes connaissances préalables (85 %)</li>\n");
      out.write("                                    <li>Les interactions avec l'équipe enseignante sont satisfaisantes (85 %)</li>\n");
      out.write("                                </ul>\n");
      out.write("                            </div>\n");
      out.write("                        </div>\n");
      out.write("                    </div>\n");
      out.write("\n");
      out.write("                    <div class=\"row pt-3\">\n");
      out.write("                        <div class=\"col-xl-12\">\n");
      out.write("                            <h5 class=\"font-weight-bold\">Propositons d'améliorations</h5>\n");
      out.write("\n");
      out.write("                            <form action=\"saveSynthesis.do\">\n");
      out.write("                                <div class=\"form-group\">\n");
      out.write("                                    <label for=\"improvementPoints\">Saissez les points d'améliorations</label>\n");
      out.write("                                    <textarea class=\"form-control\" id=\"improvementPoints\" rows=\"3\"></textarea>\n");
      out.write("                                  </div>\n");
      out.write("                                  <button type=\"submit\" class=\"btn btn-success\">Enregistrer</button>\n");
      out.write("                            </form>\n");
      out.write("                        </div>\n");
      out.write("                    </div>\n");
      out.write("\n");
      out.write("\n");
      out.write("                    <div class=\"row pt-2\">\n");
      out.write("                        <div class=\"col-xl-5\">\n");
      out.write("                            <h4>II. Réponse de l'enseignant·e responsable de la matière</h4>\n");
      out.write("                            <hr>\n");
      out.write("                        </div>\n");
      out.write("                    </div>\n");
      out.write("\n");
      out.write("\n");
      out.write("                </div>\n");
      out.write("            </div>\n");
      out.write("            <!-- End Page content -->\n");
      out.write("        </div>\n");
      out.write("        \n");
      out.write("\n");
      out.write("        \n");
      out.write("\n");
      out.write("        \n");
      out.write("    </body>\n");
      out.write("\n");
      out.write("    <script>\n");
      out.write("        $.ajax({\n");
      out.write("            'url': '/SpringApp/sidebar.do',\n");
      out.write("            'type': 'get',\n");
      out.write("            'dataType': 'html',\n");
      out.write("            beforeSend: function() {\n");
      out.write("            $(\"#sidebar_loader\").show();\n");
      out.write("            $(\"#sidebar_loader\").attr('aria-hidden', false);\n");
      out.write("            },\n");
      out.write("            success: function(msg) {\n");
      out.write("            $(\"#sidebar_loader\").hide();\n");
      out.write("            $(\"#sidebar_loader\").attr('aria-hidden', true);\n");
      out.write("            }\n");
      out.write("        })\n");
      out.write("        .done(function (response) {\n");
      out.write("            $('#Sidebar').append(response);\n");
      out.write("        })\n");
      out.write("    </script>\n");
      out.write("\n");
      out.write("\n");
      out.write("        \n");
      out.write("</html>\n");
      out.write("\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }

  private boolean _jspx_meth_c_005fset_005f0(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:set
    org.apache.taglibs.standard.tag.rt.core.SetTag _jspx_th_c_005fset_005f0 = (org.apache.taglibs.standard.tag.rt.core.SetTag) _005fjspx_005ftagPool_005fc_005fset_0026_005fvar_005fvalue_005fnobody.get(org.apache.taglibs.standard.tag.rt.core.SetTag.class);
    boolean _jspx_th_c_005fset_005f0_reused = false;
    try {
      _jspx_th_c_005fset_005f0.setPageContext(_jspx_page_context);
      _jspx_th_c_005fset_005f0.setParent(null);
      // /WEB-INF/views/surveySynthesis.jsp(9,0) name = var type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fset_005f0.setVar("scheme");
      // /WEB-INF/views/surveySynthesis.jsp(9,0) name = value type = javax.el.ValueExpression reqTime = true required = false fragment = false deferredValue = true expectedTypeName = java.lang.Object deferredMethod = false methodSignature = null
      _jspx_th_c_005fset_005f0.setValue(new org.apache.jasper.el.JspValueExpression("/WEB-INF/views/surveySynthesis.jsp(9,0) '${pageContext.request.scheme}'",_jsp_getExpressionFactory().createValueExpression(_jspx_page_context.getELContext(),"${pageContext.request.scheme}",java.lang.Object.class)).getValue(_jspx_page_context.getELContext()));
      int _jspx_eval_c_005fset_005f0 = _jspx_th_c_005fset_005f0.doStartTag();
      if (_jspx_th_c_005fset_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005fset_0026_005fvar_005fvalue_005fnobody.reuse(_jspx_th_c_005fset_005f0);
      _jspx_th_c_005fset_005f0_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fset_005f0, _jsp_getInstanceManager(), _jspx_th_c_005fset_005f0_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005fset_005f1(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:set
    org.apache.taglibs.standard.tag.rt.core.SetTag _jspx_th_c_005fset_005f1 = (org.apache.taglibs.standard.tag.rt.core.SetTag) _005fjspx_005ftagPool_005fc_005fset_0026_005fvar_005fvalue_005fnobody.get(org.apache.taglibs.standard.tag.rt.core.SetTag.class);
    boolean _jspx_th_c_005fset_005f1_reused = false;
    try {
      _jspx_th_c_005fset_005f1.setPageContext(_jspx_page_context);
      _jspx_th_c_005fset_005f1.setParent(null);
      // /WEB-INF/views/surveySynthesis.jsp(10,0) name = var type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fset_005f1.setVar("baseURL");
      // /WEB-INF/views/surveySynthesis.jsp(10,0) name = value type = javax.el.ValueExpression reqTime = true required = false fragment = false deferredValue = true expectedTypeName = java.lang.Object deferredMethod = false methodSignature = null
      _jspx_th_c_005fset_005f1.setValue(new org.apache.jasper.el.JspValueExpression("/WEB-INF/views/surveySynthesis.jsp(10,0) '${pageContext.request.localName}'",_jsp_getExpressionFactory().createValueExpression(_jspx_page_context.getELContext(),"${pageContext.request.localName}",java.lang.Object.class)).getValue(_jspx_page_context.getELContext()));
      int _jspx_eval_c_005fset_005f1 = _jspx_th_c_005fset_005f1.doStartTag();
      if (_jspx_th_c_005fset_005f1.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005fset_0026_005fvar_005fvalue_005fnobody.reuse(_jspx_th_c_005fset_005f1);
      _jspx_th_c_005fset_005f1_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fset_005f1, _jsp_getInstanceManager(), _jspx_th_c_005fset_005f1_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005fset_005f2(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:set
    org.apache.taglibs.standard.tag.rt.core.SetTag _jspx_th_c_005fset_005f2 = (org.apache.taglibs.standard.tag.rt.core.SetTag) _005fjspx_005ftagPool_005fc_005fset_0026_005fvar_005fvalue_005fnobody.get(org.apache.taglibs.standard.tag.rt.core.SetTag.class);
    boolean _jspx_th_c_005fset_005f2_reused = false;
    try {
      _jspx_th_c_005fset_005f2.setPageContext(_jspx_page_context);
      _jspx_th_c_005fset_005f2.setParent(null);
      // /WEB-INF/views/surveySynthesis.jsp(11,0) name = var type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fset_005f2.setVar("serverPort");
      // /WEB-INF/views/surveySynthesis.jsp(11,0) name = value type = javax.el.ValueExpression reqTime = true required = false fragment = false deferredValue = true expectedTypeName = java.lang.Object deferredMethod = false methodSignature = null
      _jspx_th_c_005fset_005f2.setValue(new org.apache.jasper.el.JspValueExpression("/WEB-INF/views/surveySynthesis.jsp(11,0) '${pageContext.request.serverPort}'",_jsp_getExpressionFactory().createValueExpression(_jspx_page_context.getELContext(),"${pageContext.request.serverPort}",java.lang.Object.class)).getValue(_jspx_page_context.getELContext()));
      int _jspx_eval_c_005fset_005f2 = _jspx_th_c_005fset_005f2.doStartTag();
      if (_jspx_th_c_005fset_005f2.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005fset_0026_005fvar_005fvalue_005fnobody.reuse(_jspx_th_c_005fset_005f2);
      _jspx_th_c_005fset_005f2_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fset_005f2, _jsp_getInstanceManager(), _jspx_th_c_005fset_005f2_reused);
    }
    return false;
  }
}
